### ISSUE TITLE
Duplicate params names

### ISSUE THREAD

**Issue by hbsmith** [ELIFE-ASU/datadex#6]
What happens with duplicate params names and indexing? need test for this

**Comment by dglmoore** [comment]
Once we switched to using JSON this was resolved: https://docs.python.org/3.5/library/json.html#repeated-names-within-an-object

> The RFC specifies that the names within a JSON object should be unique, but does not mandate how repeated names in JSON objects should be handled. By default, this module does not raise an exception; instead, it ignores all but the last name-value pair for a given name:
>```python
> >>> weird_json = '{"x": 1, "x": 2, "x": 3}'
> >>> json.loads(weird_json)
> {'x': 3}
>```
